export enum EnumAppointmentTypeStatus {
	CONFIRMED = 1,
	CANCELLED,
	PROPOSED,
	DONE,
	PENDING_PAYMENT,
	EXPIRED_PROPOSAL,
	NOT_DONE,
}

export const EnumAppointmentTypeStatusDetail = {
	CANCELLED_BY_PATIENT: 20,
	CANCELLED_BY_PROVIDER: 21,
	PATIENT_DID_NOT_SHOW_UP: 70,
	PATIENT_ISSUES: 71,
	PROVIDER_ISSUES: 72,
	OTHER: 73,
};

export enum EnumAlternativeProposal {
	NO_PROPOSITION = 1,
	EARLIER_ALTERNATIVE,
	ACCURATE_ALTERNATIVE,
	BOTH_ALTERNATIVES,
}
