export default {
  HOME_PAGE: 0,
  AGENDAS_PAGE: 1,
  CLIENTS_PAGE: 2,
  STAFF_PAGE: 3,
  LOCATIONS_PAGE: 4,
  SERVICES_PAGE: 5,
  USERS_PAGE: 6,
  REPORTS_PAGE: 7,
  BILLING: 8,
  PDF_CARDS_PAGE: 9,
  CARD_CREATOR: 10,
};
